// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLab.Infrastructure;

#nullable disable

namespace MusicLab.Infrastructure.Migrations
{
    [DbContext(typeof(MusicLabContext))]
    [Migration("20250501113106_AdditionalSeeding")]
    partial class AdditionalSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyMember", b =>
                {
                    b.Property<int>("CompaniesId")
                        .HasColumnType("int");

                    b.Property<int>("MembersId")
                        .HasColumnType("int");

                    b.HasKey("CompaniesId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("CompanyMember");
                });

            modelBuilder.Entity("CompanyProject", b =>
                {
                    b.Property<int>("CompaniesId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("CompaniesId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("CompanyProject");
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Los Branches"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AICOM"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Compagnie Dalché"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brussels Musical Creative"
                        });
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<int>("MeetingId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("MemberId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Meetings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "répétition chorégraphie, amenez vos chaussures",
                            EndTime = new DateTime(2025, 5, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 0,
                            Location = "Local C1",
                            Name = "Répétition du mercredi",
                            ProjectId = 1,
                            StartTime = new DateTime(2025, 5, 14, 18, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "répétition chant",
                            EndTime = new DateTime(2025, 5, 12, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 0,
                            Location = "Local B3",
                            Name = "Répétition du jeudi",
                            ProjectId = 1,
                            StartTime = new DateTime(2025, 5, 12, 18, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Travail sur la mise en scène de l'acte 2",
                            EndTime = new DateTime(2025, 5, 14, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = 0,
                            Location = "Salle Polyvalente",
                            Name = "Atelier mise en scène",
                            ProjectId = 1,
                            StartTime = new DateTime(2025, 5, 14, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Répétition complète avec costumes et décors",
                            EndTime = new DateTime(2025, 5, 18, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 0,
                            Location = "Théâtre Municipal",
                            Name = "Répétition générale",
                            ProjectId = 1,
                            StartTime = new DateTime(2025, 5, 18, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sélection pour les seconds rôles",
                            EndTime = new DateTime(2025, 5, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 5,
                            Location = "Studio 1",
                            Name = "Auditions complémentaires",
                            ProjectId = 1,
                            StartTime = new DateTime(2025, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Première représentation de la comédie musicale",
                            EndTime = new DateTime(2025, 5, 24, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 1,
                            Location = "Théâtre de la Ville",
                            Name = "Représentation publique",
                            ProjectId = 1,
                            StartTime = new DateTime(2025, 5, 24, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Présentation du budget, point sur les sponsors et choix des affiches",
                            EndTime = new DateTime(2025, 5, 15, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 2,
                            Location = "Salle B3",
                            Name = "Réunion Budget & Communication",
                            ProjectId = 1,
                            StartTime = new DateTime(2025, 5, 15, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Description = "Visite coulisses & scène, vérification matos",
                            EndTime = new DateTime(2025, 5, 15, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = 3,
                            Location = "Théâtre de la Ville",
                            Name = "Rencontre de l'équipe technique",
                            ProjectId = 1,
                            StartTime = new DateTime(2025, 5, 15, 15, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("Salt")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "henrie@branche.be",
                            Password = ":��+���+�3����m�P,���\0���ʧ)�}�6R�@�w-���w+&M��G(_D��i`$=x",
                            Role = 1,
                            Salt = new Guid("5ef564cb-6596-4592-b7bc-f21db73e1765"),
                            Username = "Henrie"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mireille@branche.be",
                            Password = "�N�QJ-���;�n��rV���T��W�И�Ÿ5I�\re�w�1�g����w����whzɁyz�",
                            Role = 0,
                            Salt = new Guid("93f1883a-2735-4595-adbc-059acb879af6"),
                            Username = "Mireille"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jeanine@branche.be",
                            Password = "^�<��d�rS!�a�<�4���G�Դ��[A���~���5�9�tiK����@�pu �'�\"�$",
                            Role = 0,
                            Salt = new Guid("93f1883a-2735-4595-adbc-059acb879af6"),
                            Username = "Jeanine"
                        },
                        new
                        {
                            Id = 4,
                            Email = "colette@branche.be",
                            Password = "C��x��O|5����nZ�(�d��M��Bӏ)oW��7Ń�i}�jn�5��u�R�pS�m]���",
                            Role = 0,
                            Salt = new Guid("93f1883a-2735-4595-adbc-059acb879af6"),
                            Username = "Colette"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lison@branche.be",
                            Password = "k�p��3�����_�e<&�\\�C�`;�7%=�A����a1M���]*�Vv,̯54N��s�BEZ�",
                            Role = 0,
                            Salt = new Guid("93f1883a-2735-4595-adbc-059acb879af6"),
                            Username = "Lison"
                        });
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.PersonalEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("PersonalEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Remplacement Gaby",
                            EndTime = new DateTime(2025, 5, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = 4,
                            Location = "Boutique Louise",
                            MemberId = 1,
                            Name = "Palais des thés",
                            StartTime = new DateTime(2025, 5, 12, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Resto fin des exams",
                            EndTime = new DateTime(2025, 5, 12, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = 4,
                            Location = "Nona Mérode",
                            MemberId = 1,
                            Name = "Resto AICOM",
                            StartTime = new DateTime(2025, 5, 12, 21, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Resto fin des exams",
                            EndTime = new DateTime(2025, 5, 12, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = 4,
                            Location = "Nona Mérode",
                            MemberId = 2,
                            Name = "Resto AICOM",
                            StartTime = new DateTime(2025, 5, 12, 21, 15, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects", t =>
                        {
                            t.HasCheckConstraint("CK_CompareDates", "startDate < endDate");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dear Evan Hansen",
                            OwnerId = 1,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateDate = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chicago",
                            OwnerId = 2,
                            StartDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "The Book of Mormon",
                            OwnerId = 1,
                            StartDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CompanyMember", b =>
                {
                    b.HasOne("MusicLab.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLab.Domain.Entities.Member", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompanyProject", b =>
                {
                    b.HasOne("MusicLab.Domain.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLab.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("MusicLab.Domain.Entities.Meeting", "Meeting")
                        .WithMany("Invitations")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicLab.Domain.Entities.Member", "Member")
                        .WithMany("Invitations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Meeting", b =>
                {
                    b.HasOne("MusicLab.Domain.Entities.Project", "Project")
                        .WithMany("Meetings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.PersonalEvent", b =>
                {
                    b.HasOne("MusicLab.Domain.Entities.Member", "Member")
                        .WithMany("PersonalEvents")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Project", b =>
                {
                    b.HasOne("MusicLab.Domain.Entities.Member", "Owner")
                        .WithMany("OwnedProjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Meeting", b =>
                {
                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Member", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("OwnedProjects");

                    b.Navigation("PersonalEvents");
                });

            modelBuilder.Entity("MusicLab.Domain.Entities.Project", b =>
                {
                    b.Navigation("Meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
